WIP: bashrc

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -24,4 +24,140 @@ case "$TERM" in
     xterm-color|*-256color) color_prompt=yes;;
 esac
 
-fish
+# Set environment
+export EDITOR='nvim'
+export GREP_COLOR='1;36'
+export LSCOLORS='ExGxbEaECxxEhEhBaDaCaD'
+
+# Shell Options
+shopt -s cdspell
+shopt -s extglob
+shopt -s autocd   2>/dev/null || true
+shopt -s dirspell 2>/dev/null || true
+
+# Aliases
+alias e='nvim'
+alias vi='nvim'
+alias vim='nvim'
+
+alias ..='cd..; ls'
+alias p='pwd; ls'
+
+alias des='cd $HOME/Desktop; ls'
+alias dow='cd $HOME/Downloads; ls'
+alias home='cd $HOME; ls'
+alias repo='cd $HOME/repo; ls'
+
+alias c='clear'
+alias l='ls -lhvF'
+alias ls='ls -lhvF'
+
+alias du='du -h'
+alias du0='du -sh * | sort -hr'
+alias du1='du -hxd 1 | sort -hr'
+
+alias cp='cp -v'
+alias mv='mv -v'
+alias rm='rm -v'
+alias rsync='rsync-v'
+
+alias procs='ps aux | grep $USER'
+alias ports='netstat -tulna'
+
+alias g='git'
+alias tm='tmux -f $HOME/.config/tmux/tmux.conf'
+alias upd='sudo apt update && suo apt upgrade -y'
+
+alias grep='grep --color=auto'
+alias ls='ls -p --color=auto'
+
+# Prompt
+# Store `tput` colors for future use to reduce fork+exec
+# the array will be 0-255 for colors, 256 will be sgr0
+# and 257 will be bold
+COLOR256=()
+COLOR256[0]=$(tput setaf 1)
+COLOR256[256]=$(tput sgr0)
+COLOR256[257]=$(tput bold)
+
+# Colors for use in PS1 that may or may not change when
+# set_prompt_colors is run
+PROMPT_COLORS=()
+
+# Change the prompt colors to a theme, themes are 0-29
+set_prompt_colors() {
+	local h=${1:-0}
+	local color=
+	local i=0
+	local j=0
+	for i in {22..231}; do
+		((i % 30 == h)) || continue
+
+		color=${COLOR256[$i]}
+		# cache the tput colors
+		if [[ -z $color ]]; then
+			COLOR256[$i]=$(tput setaf "$i")
+			color=${COLOR256[$i]}
+		fi
+		PROMPT_COLORS[$j]=$color
+		((j++))
+	done
+}
+
+# Construct the prompt
+# [(exit code)] <user> - <hostname> <uname> <cwd> [git branch] <$|#>
+
+# exit code of last process
+PS1='$(ret=$?;(($ret!=0)) && echo "\[${COLOR256[0]}\]($ret) \[${COLOR256[256]}\]")'
+
+# username (red for root)
+PS1+='\[${PROMPT_COLORS[0]}\]\[${COLOR256[257]}\]$(((UID==0)) && echo "\[${COLOR256[0]}\]")\u\[${COLOR256[256]}\] - '
+
+# zonename (global zone warning)
+PS1+='\[${COLOR256[0]}\]\[${COLOR256[257]}\]'"$(zonename 2>/dev/null | grep -q '^global$' && echo 'GZ:')"'\[${COLOR256[256]}\]'
+
+# hostname
+PS1+='\[${PROMPT_COLORS[3]}\]\h '
+
+# uname
+PS1+='\[${PROMPT_COLORS[2]}\]'"$(uname | tr '[:upper:]' '[:lower:]')"' '
+
+# cwd
+PS1+='\[${PROMPT_COLORS[5]}\]\w '
+
+# optional git branch
+PS1+='$(branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null); [[ -n $branch ]] && echo "\[${PROMPT_COLORS[2]}\](\[${PROMPT_COLORS[3]}\]git:$branch\[${PROMPT_COLORS[2]}\]) ")'
+
+# prompt character
+PS1+='\[${PROMPT_COLORS[0]}\]\$\[${COLOR256[256]}\] '
+
+# set the theme
+set_prompt_colors 24
+
+# Prompt command
+_prompt_command() {
+        local user=$USER
+        local host=${HOSTNAME%%.*}
+        local pwd=${PWD/#$HOME/\~}
+        local ssh=
+        [[ -n $SSH_CLIENT ]] && ssh='[ssh] '
+        printf "\033]0;%s%s@%s:%s\007" "$ssh" "$user" "$host" "$pwd"
+}
+PROMPT_COMMAND=_prompt_command
+
+PROMPT_DIRTRIM=6
+
+# Print all 256 colors
+colors() {
+	local i
+	for i in {0..255}; do
+		printf "\x1b[38;5;${i}mcolor %d\n" "$i"
+	done
+	tput sgr0
+}
+
+# load completion
+. /etc/bash/bash_completion 2>/dev/null ||
+	. ~/.bash_completion 2>/dev/null
+
+true
